name: Build MkDocs into /docs

on:
  push:
    branches: [ main ]
    # Avoid infinite loops when we commit generated /docs
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs + theme
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Build site into /docs
        run: mkdocs build --strict  # uses site_dir: docs from mkdocs.yml

      - name: Ensure .nojekyll exists
        run: touch docs/.nojekyll

      - name: Commit and push updated /docs
        run: |
          if [ -n "$(git status --porcelain docs)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A docs
            git commit -m "docs: rebuild site [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

